apiVersion: v1
kind: Service
metadata:
  name: myapp-service   # Tên của Service
spec:
  type: LoadBalancer    # Loại Service, LoadBalancer sẽ phân phối lưu lượng từ mạng bên ngoài
  ports:
    - port: 80          # Cổng mà Service sẽ lắng nghe trên mạng bên ngoài
      targetPort: 80    # Cổng mà Service sẽ gửi lưu lượng đến trong các Pods
      protocol: TCP     # Giao thức mạng được sử dụng (TCP là thông dụng nhất)
  selector:
    app: myapp          # Selector để tìm các Pods mà Service này sẽ gửi lưu lượng đến
